spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ttrip-db:3306/coredb
    username: root
    password: ttrip104!

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://root:ttrip104!@mongo-db:27017/chatDB?authSource=admin