spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/coredb  #test코드 실행할 때는 localhost로 변경
    username: root
    password: ttrip104!

  redis:
    host: localhost
    port: 6379
    password: ttrip104!

flask:
  baseurl: 'http://localhost:5000'

  data:
    monogodb:
      uri: mongodb://root:root@localhost:27017/chatDB?authSource=admin