server:
  port: 8081

spring:
  profiles:
    active: prod # 기본 환경을 prod로 셋팅 local 개발할때는 local로 바꾸세요.

  hikari:
    connectionTimeout : 30000
    maximumPoolSize : 30
    maxLifeTime : 97
    poolName : HikariCP
    readOnly : false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        type:
          preferred_uuid_jdbc_type: CHAR
    #    show_sql: true #show sql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: redis-db
    port: 6379
    password: ttrip104!

logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframework:
        web:
          socket:
            messaging:
              WebSocketMessageHandler: TRACE
        messaging:
          simp:
            user:
              SimpUserRegistry: TRACE
            stomp:
              StompDecoder: TRACE
              StompEncoder: TRACE

custom:
  path:
    upload-images: '/var/lib/images'

jwt:
  secret: 52099f75a38f208a0c873b4c2ae43aaf72a4ac0898d713a8ab22d8c57a439f5dada15dcd23d857971fc4d48f8c8df038a2f0044de2bc8b6817ed5bc9ae1ea43b