spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ttrip-db:3306/coredb
    username: root
    password: ttrip104!

  jpa:
    hibernate:
      ddl-auto: none
