spring:
  batch-db:
    datasource:
      jdbc-url: jdbc:mariadb://ttrip-db:3306/batchdb
      username: root
      password: ttrip104!
  core-db:
    datasource:
      jdbc-url: jdbc:mariadb://ttrip-db:3306/coredb
      username: root
      password: ttrip104!

  jpa:
    hibernate:
      ddl-auto: none